In [20]:
import numpy as np

Write a simple Hamming encoder program in Python, which, when given a 4-bit binary value, returns the resulting 7-bit binary vector codeword. 
Also implement the parity check functionality to see if there are any errors, that is to check whether H ∗ cw = 0 holds, where is zero vector.

In [21]:
GeneratorMatrix = np.array([[1, 1, 0, 1],
                         [1, 0, 1, 1],
                         [1, 0, 0, 0],
                         [0, 1, 1, 1],
                         [0, 1, 0, 0],
                         [0, 0, 1, 0],
                         [0, 0, 0, 1]])

ParityCheckMatrix = np.array([[1, 0, 1, 0, 1, 0, 1],
                             [0, 1, 1, 0, 0, 1, 1],
                             [0, 0, 0, 1, 1, 1, 1]])

DecoderMatrix = np.array([[0, 0, 1, 0, 0, 0, 0],
                         [0, 0, 0, 0, 1, 0, 0],
                         [0, 0, 0, 0, 0, 1, 0],
                         [0, 0, 0, 0, 0, 0, 1]])

In [129]:
# Function takes 4-digit number and transforms number into an array consisting of those four elements
# Resulting array is used to calculate 7-digit codeword with the help of the Generator Matrix (G)
codeword = None

def codeword_generator(x):
    
    global codeword
    lst = [int(i) for i in str(x)]
    if len(lst) != 4:
        raise ValueError("Code must consist of four digits.")
    resulting_array = np.array(lst)
    
    preliminary_codeword = np.dot(GeneratorMatrix, resulting_array)

    # GF(2) arithmetic: put a 1 in our 7-digit codeword, if number is odd and out a 0, if the number is even (e.g., if the resulting number is 2 due to 
    # two times 1, put a 0 to the resulting codeword, since it may only contain 0s and 1s.)
    codeword_lst = []
    for i in preliminary_codeword:
        if i%2 == 0:
            codeword_lst.append(0)
        else:
            codeword_lst.append(1)

    codeword = np.array(codeword_lst)
    return codeword

# Multiplying the codeword with the Parity-check Matrix (H) must result in the zero Vector
# x is the codeword from the first function
# if codeword is artificially generated (with bitflip), x is the artificially generated codeword
def parity_check(x):

    first_check = np.dot(ParityCheckMatrix, x)
    # create array containing of 0s and 1s
    #error_syndrome_lst = [1 if i%2 != 0 else 0 for i in first_check]
    #error_syndrome = np.array(error_syndrome_lst)
    error_syndrome = np.mod(first_check, 2)
    print(f'The error vector is {error_syndrome}.')
    if np.sum(error_syndrome) == 0:
        print(f'There was no error occuring upon code-transmission.')
    else:
        transposed_parity = ParityCheckMatrix.transpose()
        list_parity = transposed_parity.tolist()
        list_index = list_parity.index(error_syndrome.tolist())
        matrix_row_index = list_index + 1
        #condition = transposed_parity == error_syndrome
        #matrix_row_index = np.where(condition)[0]
        print(f'There was an error eoccuring upon code-transmission.\nThe Bitflip occured at the {matrix_row_index}th position.')
    return

# decoder function returns 'original' 4-bit vector when given a 7-bit codeword
def decoder(x):

    if type(x) is not np.ndarray:
        x = np.array(x)

    if (x.shape[0] != 7) and (x.shape[1] != 1):
        raise ValueError ('Function can only decode vectors of shape [7, 1].')
    
    decoded = np.dot(DecoderMatrix, x)
    print(decoded)
    binary_decoded = np.mod(decoded, 2)
    print(binary_decoded)
    return (f'The original 4-bit vector is {binary_decoded}.')

In [130]:
example1 = 1010

codeword_generator(example1)

array([1, 0, 1, 1, 0, 1, 0])

In [123]:
parity_check(codeword)

The error vector is [0 0 0].
There was no error occuring upon code-transmission.


In [131]:
decoder(codeword)

[1 0 1 0]
[1 0 1 0]


'The original 4-bit vector is [1 0 1 0].'

In [132]:
example2 = 1001
print(codeword_generator(example2))
print(parity_check(codeword))
print(decoder(codeword))

[0 0 1 1 0 0 1]
The error vector is [0 0 0].
There was no error occuring upon code-transmission.
None
[1 0 0 1]
[1 0 0 1]
The original 4-bit vector is [1 0 0 1].


In [133]:
example3 = 1011
print(codeword_generator(example3))
print(parity_check(codeword))
print(decoder(codeword))

[0 1 1 0 0 1 1]
The error vector is [0 0 0].
There was no error occuring upon code-transmission.
None
[1 0 1 1]
[1 0 1 1]
The original 4-bit vector is [1 0 1 1].


In [116]:
# Artificial codeword with Bitflip at the 4th position (compared to 7-bit vector codeword of example1 [1, 0, 1, 1, 0, 1, 0])
neg_ex1 = [1, 0, 1, 0, 0, 1, 0]
negative_example1 = np.array(neg_ex1)
parity_check(negative_example1)

The error vector is [0 0 1].
There was an error eoccuring upon code-transmission.
The Bitflip occured at the 4th position.


In [134]:
# Artificial codeword with Bitflip at the 6th position (compared to 7-bit vector codeword of example2 [0, 0, 1, 1, 0, 0, 1])
neg_ex2 = [0, 0, 1, 1, 0, 1, 1]
negative_example2 = np.array(neg_ex2)
parity_check(negative_example2)

The error vector is [0 1 1].
There was an error eoccuring upon code-transmission.
The Bitflip occured at the 6th position.


In [135]:
# Artificial codeword with Bitflip at the 1th position (compared to 7-bit vector codeword of example3 [0, 1, 1, 0, 0, 1, 1])
neg_ex3 = [1, 1, 1, 0, 0, 1, 1]
negative_example3 = np.array(neg_ex3)
parity_check(negative_example3)

The error vector is [1 0 0].
There was an error eoccuring upon code-transmission.
The Bitflip occured at the 1th position.


Examples for showcasing that partiy check functionality cannot check vectors with two-bit errors.

In [136]:
# Artificial codeword with Bitflips at the 4th and 6th position (compared to 7-bit vector codeword of example1 [1, 0, 1, 1, 0, 1, 0])
extreme_neg_ex1 = [1, 0, 1, 0, 0, 0, 0]
extr_negative_example1 = np.array(extreme_neg_ex1)
parity_check(extr_negative_example1)

The error vector is [0 1 0].
There was an error eoccuring upon code-transmission.
The Bitflip occured at the 2th position.


Parity check function puts forward that the bitflip occured at the second position. This is not correct, since there were two bitflips occurring at the positions of the 4th and 6th elements (3rd and 5th index). This is, according to "Coding the Matrix" by Philip N. Klein Page 213, that there are multiple acceptable answers that satisfy the condition of H * e1 = H * e2.